FROM alpine:slim

# Instala o mingw-w64
RUN apt-get update && \
    apt-get install -y mingw-w64

# Defina o diretório de trabalho
WORKDIR /workspace

# Copie o código-fonte para o contêiner
COPY . .

# Compila o código-fonte
# Substitua 'install_coder.c' pelo seu arquivo de origem e 'coder_installer.exe' pelo nome desejado do executável de saída
RUN x86_64-w64-mingw32-gcc install/install_coder.c -o build/windows/coder_installer.exe

# Comando padrão
CMD ["./build/windows/coder_installer.exe"]