/**
 * Capabilities Comparison Tool with Progress Tracking
 * 
 * This script compares the LLM-Capabilities sheet (generated by search_llm_capabilities.gs)
 * with the IDE-Capabilities sheet to identify any discrepancies in capability status.
 * It includes progress tracking to monitor the execution.
 */

// Configuration constants - renamed to avoid conflict with other scripts
const COMPARE_CONFIG = {
  SOURCE_SHEET_NAME: "LLM-Capabilities",
  TARGET_SHEET_NAME: "IDE-Capabilities",
  REPORT_SHEET_NAME: "Comparison-Report",
  PROGRESS_SHEET_NAME: "Progress-Tracker",
  STATUS: {
    ENABLE: "Enable",
    DISABLE: "Disable"
  },
  COLORS: {
    TITLE_BG: "#000000",
    TITLE_TEXT: "#FFFFFF",
    HEADER_BG: "#D3D3D3",
    ERROR_BG: "#FFCCCB",
    SUCCESS_BG: "#90EE90",
    ENABLE_BG: "#90EE90",  // Verde para Enable
    DISABLE_BG: "#FFCCCB",  // Vermelho para Disable
    PROGRESS_BG: "#E6F2FF"  // Azul claro para progresso
  }
};

/**
 * Creates custom menu when spreadsheet is opened
 */
function onOpen() {
  const ui = SpreadsheetApp.getUi();
  ui.createMenu('Comparar Planilhas')
      .addItem('Comparar Status de Capabilities', 'compareCapabilities')
      .addToUi();
}

/**
 * Main function to compare capabilities between sheets
 */
function compareCapabilities() {
  try {
    const spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
    
    // Create progress tracker
    const progressTracker = _createProgressTracker(spreadsheet);
    progressTracker.update("Iniciando comparação...", 0);
    
    // Get source and target sheets
    progressTracker.update("Carregando planilhas...", 5);
    const sourceSheet = spreadsheet.getSheetByName(COMPARE_CONFIG.SOURCE_SHEET_NAME);
    const targetSheet = spreadsheet.getSheetByName(COMPARE_CONFIG.TARGET_SHEET_NAME);
    
    // Validate sheets exist
    if (!sourceSheet) {
      progressTracker.update("ERRO: Planilha fonte não encontrada", 100);
      throw new Error(`Planilha "${COMPARE_CONFIG.SOURCE_SHEET_NAME}" não encontrada. Execute o script search_llm_capabilities.gs primeiro.`);
    }
    
    if (!targetSheet) {
      progressTracker.update("ERRO: Planilha alvo não encontrada", 100);
      throw new Error(`Planilha "${COMPARE_CONFIG.TARGET_SHEET_NAME}" não encontrada.`);
    }
    
    // Create or clear report sheet
    progressTracker.update("Preparando planilha de relatório...", 10);
    const reportSheet = _prepareReportSheet(spreadsheet);
    
    // Get data from both sheets including cell backgrounds
    progressTracker.update("Carregando dados da planilha fonte...", 15);
    const sourceData = _getSheetDataWithFormatting(sourceSheet, progressTracker);
    
    progressTracker.update("Carregando dados da planilha alvo...", 30);
    const targetData = _getSheetDataWithFormatting(targetSheet, progressTracker);
    
    // Create lookup maps for faster comparison
    progressTracker.update("Criando mapas de busca para comparação rápida...", 45);
    const sourceMap = _createLookupMap(sourceData.rows, sourceData.backgrounds);
    const targetMap = _createLookupMap(targetData.rows, targetData.backgrounds);
    
    // Compare data and generate report
    progressTracker.update("Comparando dados...", 50);
    const discrepancies = _compareData(sourceData, targetData, sourceMap, targetMap, progressTracker);
    
    // Display report
    progressTracker.update("Gerando relatório...", 80);
    _displayReport(reportSheet, discrepancies, sourceData.headers, progressTracker);
    
    // Complete progress
    progressTracker.update("Comparação concluída!", 100);
    
    // Show completion message
    const message = discrepancies.length > 0 
      ? `Comparação concluída. Foram encontradas ${discrepancies.length} divergências de status.` 
      : "Comparação concluída. Nenhuma divergência de status encontrada!";
    
    SpreadsheetApp.getUi().alert("Resultado da Comparação", message, SpreadsheetApp.getUi().ButtonSet.OK);
    
  } catch (error) {
    SpreadsheetApp.getUi().alert("Erro: " + error.message);
  }
}

// =============================================================================
// Progress Tracking Functions
// =============================================================================

/**
 * Creates a progress tracker in a separate sheet
 * @param {Object} spreadsheet - Spreadsheet object
 * @return {Object} Progress tracker object with update method
 * @private
 */
function _createProgressTracker(spreadsheet) {
  // Check if progress sheet already exists and delete it
  let progressSheet = spreadsheet.getSheetByName(COMPARE_CONFIG.PROGRESS_SHEET_NAME);
  if (progressSheet) {
    spreadsheet.deleteSheet(progressSheet);
  }
  
  // Create new progress sheet
  progressSheet = spreadsheet.insertSheet(COMPARE_CONFIG.PROGRESS_SHEET_NAME);
  
  // Set up progress sheet
  progressSheet.getRange("A1:B1").merge();
  progressSheet.getRange("A1").setValue("MONITORAMENTO DE PROGRESSO DA COMPARAÇÃO")
    .setFontWeight("bold")
    .setBackground(COMPARE_CONFIG.COLORS.TITLE_BG)
    .setFontColor(COMPARE_CONFIG.COLORS.TITLE_TEXT)
    .setHorizontalAlignment("center");
  
  progressSheet.getRange("A2").setValue("Status Atual:");
  progressSheet.getRange("A3").setValue("Progresso:");
  progressSheet.getRange("A4").setValue("Linha Atual:");
  progressSheet.getRange("A5").setValue("Coluna Atual:");
  progressSheet.getRange("A6").setValue("Tempo Decorrido:");
  
  progressSheet.getRange("B2:B6").setBackground(COMPARE_CONFIG.COLORS.PROGRESS_BG);
  
  // Create progress bar
  progressSheet.getRange("A8").setValue("Barra de Progresso:");
  progressSheet.getRange("A9:J9").setBorder(true, true, true, true, false, false);
  
  // Set column widths
  progressSheet.setColumnWidth(1, 150);
  progressSheet.setColumnWidth(2, 300);
  
  // Start timer
  const startTime = new Date();
  
  // Return progress tracker object
  return {
    update: function(status, percentComplete, currentRow, currentColumn) {
      // Update status
      progressSheet.getRange("B2").setValue(status);
      
      // Update progress percentage
      progressSheet.getRange("B3").setValue(Math.round(percentComplete) + "%");
      
      // Update current row and column if provided
      if (currentRow !== undefined) {
        progressSheet.getRange("B4").setValue(currentRow);
      }
      
      if (currentColumn !== undefined) {
        progressSheet.getRange("B5").setValue(currentColumn);
      }
      
      // Update elapsed time
      const currentTime = new Date();
      const elapsedSeconds = Math.floor((currentTime - startTime) / 1000);
      const minutes = Math.floor(elapsedSeconds / 60);
      const seconds = elapsedSeconds % 60;
      progressSheet.getRange("B6").setValue(`${minutes}m ${seconds}s`);
      
      // Update progress bar
      const filledCells = Math.floor(percentComplete / 10);
      for (let i = 0; i < 10; i++) {
        const cell = progressSheet.getRange(9, i + 1);
        if (i < filledCells) {
          cell.setBackground("#4285F4"); // Google blue
        } else {
          cell.setBackground("#FFFFFF");
        }
      }
      
      // Force the spreadsheet to update visually
      SpreadsheetApp.flush();
    }
  };
}

// =============================================================================
// Private Helper Functions
// =============================================================================

/**
 * Prepares the report sheet
 * @param {Object} spreadsheet - Spreadsheet object
 * @return {Object} Report sheet object
 * @private
 */
function _prepareReportSheet(spreadsheet) {
  let reportSheet = spreadsheet.getSheetByName(COMPARE_CONFIG.REPORT_SHEET_NAME);
  
  if (reportSheet) {
    // Clear existing content if sheet exists
    reportSheet.clear();
  } else {
    // Create new sheet if it doesn't exist
    reportSheet = spreadsheet.insertSheet(COMPARE_CONFIG.REPORT_SHEET_NAME);
  }
  
  return reportSheet;
}

/**
 * Gets data from a sheet including headers, rows, and cell backgrounds
 * @param {Object} sheet - Sheet object
 * @param {Object} progressTracker - Progress tracker object
 * @return {Object} Object containing headers, rows, and backgrounds
 * @private
 */
function _getSheetDataWithFormatting(sheet, progressTracker) {
  const lastRow = sheet.getLastRow();
  const lastColumn = sheet.getLastColumn();
  
  // Update progress with sheet dimensions
  progressTracker.update(`Carregando dados de ${sheet.getName()} (${lastRow} linhas, ${lastColumn} colunas)...`, 
                         sheet.getName() === COMPARE_CONFIG.SOURCE_SHEET_NAME ? 20 : 35);
  
  // Get title from row 1
  const titleRange = sheet.getRange(1, 1, 1, lastColumn);
  const title = titleRange.getValues()[0][0];
  
  // Get headers from row 2
  const headerRange = sheet.getRange(2, 1, 1, lastColumn);
  const headers = headerRange.getValues()[0];
  
  // Get data rows (starting from row 3)
  const dataRange = sheet.getRange(3, 1, lastRow - 2, lastColumn);
  
  // Update progress before potentially long operations
  progressTracker.update(`Carregando valores de ${sheet.getName()}...`, 
                         sheet.getName() === COMPARE_CONFIG.SOURCE_SHEET_NAME ? 22 : 37);
  const rows = dataRange.getValues();
  
  progressTracker.update(`Carregando formatação de ${sheet.getName()}...`, 
                         sheet.getName() === COMPARE_CONFIG.SOURCE_SHEET_NAME ? 25 : 40);
  const backgrounds = dataRange.getBackgrounds();
  
  return {
    title: title,
    headers: headers,
    rows: rows,
    backgrounds: backgrounds
  };
}

/**
 * Compares data between source and target sheets
 * @param {Object} sourceData - Source sheet data
 * @param {Object} targetData - Target sheet data
 * @param {Object} sourceMap - Source lookup map
 * @param {Object} targetMap - Target lookup map
 * @param {Object} progressTracker - Progress tracker object
 * @return {Array} Array of discrepancies
 * @private
 */
function _compareData(sourceData, targetData, sourceMap, targetMap, progressTracker) {
  const discrepancies = [];
  
  // Check if headers match
  progressTracker.update("Verificando correspondência de cabeçalhos...", 52);
  if (!_arraysEqual(sourceData.headers, targetData.headers)) {
    discrepancies.push({
      type: "header",
      message: "Os cabeçalhos das planilhas não correspondem",
      sourceHeaders: sourceData.headers,
      targetHeaders: targetData.headers
    });
    return discrepancies; // Stop comparison if headers don't match
  }
  
  // Compare source to target
  progressTracker.update("Comparando status de capabilities...", 55);
  _findStatusDiscrepancies(sourceData, targetData, sourceMap, targetMap, discrepancies, progressTracker);
  
  // Compare target to source (to find models in target that don't exist in source)
  progressTracker.update("Verificando modelos ausentes...", 75);
  _findMissingModels(sourceData, targetData, sourceMap, targetMap, discrepancies, progressTracker);
  
  return discrepancies;
}

/**
 * Creates a lookup map for faster data access
 * @param {Array} rows - Data rows
 * @param {Array} backgrounds - Cell backgrounds
 * @return {Object} Lookup map
 * @private
 */
function _createLookupMap(rows, backgrounds) {
  const map = {};
  
  rows.forEach((row, rowIndex) => {
    const provider = row[0];
    const model = row[1];
    const key = `${provider}|${model}`;
    
    map[key] = {
      rowIndex: rowIndex,
      data: row,
      backgrounds: backgrounds ? backgrounds[rowIndex] : null
    };
  });
  
  return map;
}

/**
 * Finds status discrepancies between source and target data
 * @param {Object} sourceData - Source sheet data
 * @param {Object} targetData - Target sheet data
 * @param {Object} sourceMap - Source lookup map
 * @param {Object} targetMap - Target lookup map
 * @param {Array} discrepancies - Array to store discrepancies
 * @param {Object} progressTracker - Progress tracker object
 * @private
 */
function _findStatusDiscrepancies(sourceData, targetData, sourceMap, targetMap, discrepancies, progressTracker) {
  const totalRows = sourceData.rows.length;
  
  sourceData.rows.forEach((sourceRow, sourceRowIndex) => {
    const provider = sourceRow[0];
    const model = sourceRow[1];
    const key = `${provider}|${model}`;
    
    // Update progress for each model (distribute progress from 55% to 70%)
    const progressPercent = 55 + Math.floor((sourceRowIndex / totalRows) * 15);
    progressTracker.update(`Comparando modelo: ${provider} - ${model}`, 
                          progressPercent, 
                          sourceRowIndex + 3, // +3 because data starts at row 3
                          "");
    
    if (targetMap[key]) {
      // Model exists in both sheets, compare capability status
      const targetRow = targetMap[key].data;
      const sourceBackgrounds = sourceData.backgrounds[sourceRowIndex];
      const targetBackgrounds = targetMap[key].backgrounds;
      
      for (let colIndex = 2; colIndex < sourceRow.length; colIndex++) {
        // Update column in progress tracker every 5 columns to avoid too many updates
        if (colIndex % 5 === 0) {
          progressTracker.update(`Comparando modelo: ${provider} - ${model}, coluna: ${_columnToLetter(colIndex + 1)}`, 
                                progressPercent, 
                                sourceRowIndex + 3, 
                                _columnToLetter(colIndex + 1));
        }
        
        const sourceStatus = sourceRow[colIndex];
        const targetStatus = targetRow[colIndex];
        
        // Compare status values (Enable/Disable)
        if (sourceStatus !== targetStatus) {
          discrepancies.push({
            type: "status",
            provider: provider,
            model: model,
            capability: sourceData.headers[colIndex],
            sourceStatus: sourceStatus,
            targetStatus: targetStatus,
            sourceRowIndex: sourceRowIndex + 3, // +3 because data starts at row 3
            targetRowIndex: targetMap[key].rowIndex + 3,
            columnIndex: colIndex + 1, // +1 because arrays are 0-indexed
            sourceBackground: sourceBackgrounds[colIndex],
            targetBackground: targetBackgrounds[colIndex]
          });
        }
      }
    } else {
      // Model exists in source but not in target
      discrepancies.push({
        type: "missing_model",
        provider: provider,
        model: model,
        location: "target",
        rowIndex: sourceRowIndex + 3
      });
    }
  });
}

/**
 * Finds models that exist in target but not in source
 * @param {Object} sourceData - Source sheet data
 * @param {Object} targetData - Target sheet data
 * @param {Object} sourceMap - Source lookup map
 * @param {Object} targetMap - Target lookup map
 * @param {Array} discrepancies - Array to store discrepancies
 * @param {Object} progressTracker - Progress tracker object
 * @private
 */
function _findMissingModels(sourceData, targetData, sourceMap, targetMap, discrepancies, progressTracker) {
  const totalRows = targetData.rows.length;
  
  targetData.rows.forEach((targetRow, targetRowIndex) => {
    const provider = targetRow[0];
    const model = targetRow[1];
    const key = `${provider}|${model}`;
    
    // Update progress (distribute from 75% to 80%)
    const progressPercent = 75 + Math.floor((targetRowIndex / totalRows) * 5);
    progressTracker.update(`Verificando modelo ausente: ${provider} - ${model}`, 
                          progressPercent, 
                          targetRowIndex + 3, 
                          "");
    
    if (!sourceMap[key]) {
      // Model exists in target but not in source
      discrepancies.push({
        type: "missing_model",
        provider: provider,
        model: model,
        location: "source",
        rowIndex: targetRowIndex + 3
      });
    }
  });
}

/**
 * Displays the comparison report
 * @param {Object} reportSheet - Report sheet object
 * @param {Array} discrepancies - Array of discrepancies
 * @param {Array} headers - Headers from source sheet
 * @param {Object} progressTracker - Progress tracker object
 * @private
 */
function _displayReport(reportSheet, discrepancies, headers, progressTracker) {
  // Add title
  progressTracker.update("Criando título do relatório...", 81);
  _addReportTitle(reportSheet);
  
  if (discrepancies.length === 0) {
    // No discrepancies found
    progressTracker.update("Nenhuma discrepância encontrada, finalizando relatório...", 95);
    _addNoDiscrepanciesMessage(reportSheet);
    return;
  }
  
  // Add summary
  progressTracker.update("Adicionando resumo ao relatório...", 83);
  _addSummary(reportSheet, discrepancies);
  
  // Add report headers
  progressTracker.update("Adicionando cabeçalhos ao relatório...", 85);
  _addReportHeaders(reportSheet);
  
  // Add discrepancies
  progressTracker.update("Adicionando discrepâncias ao relatório...", 87);
  _addDiscrepancies(reportSheet, discrepancies, headers, progressTracker);
  
  // Format report
  progressTracker.update("Formatando relatório...", 95);
  _formatReport(reportSheet);
}

/**
 * Adds title to report
 * @param {Object} sheet - Report sheet object
 * @private
 */
function _addReportTitle(sheet) {
  sheet.appendRow(['']);
  const titleRange = sheet.getRange(1, 1, 1, 8);
  titleRange.merge();
  titleRange.setValue("RELATÓRIO DE COMPARAÇÃO DE STATUS DE CAPABILITIES");
  titleRange.setFontWeight("bold");
  titleRange.setBackground(COMPARE_CONFIG.COLORS.TITLE_BG);
  titleRange.setFontColor(COMPARE_CONFIG.COLORS.TITLE_TEXT);
  titleRange.setHorizontalAlignment("center");
  titleRange.setVerticalAlignment("middle");
  sheet.setRowHeight(1, 30);
}

/**
 * Adds summary of discrepancies
 * @param {Object} sheet - Report sheet object
 * @param {Array} discrepancies - Array of discrepancies
 * @private
 */
function _addSummary(sheet, discrepancies) {
  // Count discrepancies by type
  let statusCount = 0;
  let missingModelCount = 0;
  let headerIssue = false;
  
  discrepancies.forEach(d => {
    if (d.type === "status") statusCount++;
    else if (d.type === "missing_model") missingModelCount++;
    else if (d.type === "header") headerIssue = true;
  });
  
  // Add summary row
  sheet.appendRow(['']);
  const summaryRange = sheet.getRange(2, 1, 1, 8);
  summaryRange.merge();
  
  let summaryText = `RESUMO: Encontradas ${discrepancies.length} divergências no total.`;
  if (statusCount > 0) summaryText += ` ${statusCount} divergências de status.`;
  if (missingModelCount > 0) summaryText += ` ${missingModelCount} modelos ausentes.`;
  if (headerIssue) summaryText += " Problema nos cabeçalhos das planilhas.";
  
  summaryRange.setValue(summaryText);
  summaryRange.setFontWeight("bold");
  summaryRange.setBackground("#FFD700"); // Amarelo para destaque
  summaryRange.setHorizontalAlignment("center");
  summaryRange.setVerticalAlignment("middle");
  sheet.setRowHeight(2, 30);
}

/**
 * Adds message when no discrepancies are found
 * @param {Object} sheet - Report sheet object
 * @private
 */
function _addNoDiscrepanciesMessage(sheet) {
  sheet.appendRow(['']);
  const messageRange = sheet.getRange(2, 1, 1, 8);
  messageRange.merge();
  messageRange.setValue("Nenhuma divergência de status encontrada. Os status das capabilities são idênticos em ambas as planilhas.");
  messageRange.setFontWeight("bold");
  messageRange.setBackground(COMPARE_CONFIG.COLORS.SUCCESS_BG);
  messageRange.setHorizontalAlignment("center");
  messageRange.setVerticalAlignment("middle");
  sheet.setRowHeight(2, 30);
}

/**
 * Adds report headers
 * @param {Object} sheet - Report sheet object
 * @private
 */
function _addReportHeaders(sheet) {
  const headers = [
    'Tipo de Divergência',
    'Provider',
    'Modelo',
    'Capability',
    'Status em LLM-Capabilities',
    'Status em IDE-Capabilities',
    'Localização',
    'Ação Recomendada'
  ];
  
  sheet.appendRow(['']);
  sheet.appendRow(headers);
  
  const headerRange = sheet.getRange(4, 1, 1, headers.length);
  headerRange.setFontWeight("bold");
  headerRange.setBackground(COMPARE_CONFIG.COLORS.HEADER_BG);
  headerRange.setHorizontalAlignment("center");
  headerRange.setVerticalAlignment("middle");
}

/**
 * Adds discrepancies to report
 * @param {Object} sheet - Report sheet object
 * @param {Array} discrepancies - Array of discrepancies
 * @param {Array} headers - Headers from source sheet
 * @param {Object} progressTracker - Progress tracker object
 * @private
 */
function _addDiscrepancies(sheet, discrepancies, headers, progressTracker) {
  let rowIndex = 5; // Start after headers
  const totalDiscrepancies = discrepancies.length;
  
  discrepancies.forEach((discrepancy, index) => {
    // Update progress (distribute from 87% to 95%)
    const progressPercent = 87 + Math.floor((index / totalDiscrepancies) * 8);
    progressTracker.update(`Adicionando discrepância ${index + 1} de ${totalDiscrepancies} ao relatório...`, 
                          progressPercent);
    
    let row = [];
    
    if (discrepancy.type === "header") {
      row = [
        "Cabeçalhos Diferentes",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "Verificar e alinhar os cabeçalhos das planilhas"
      ];
      sheet.appendRow(row);
    } else if (discrepancy.type === "missing_model") {
      const location = discrepancy.location === "source" 
        ? `Modelo existe apenas em ${COMPARE_CONFIG.TARGET_SHEET_NAME} (linha ${discrepancy.rowIndex})` 
        : `Modelo existe apenas em ${COMPARE_CONFIG.SOURCE_SHEET_NAME} (linha ${discrepancy.rowIndex})`;
      
      const action = discrepancy.location === "source"
        ? `Adicionar modelo ao ${COMPARE_CONFIG.SOURCE_SHEET_NAME}`
        : `Adicionar modelo ao ${COMPARE_CONFIG.TARGET_SHEET_NAME}`;
      
      row = [
        "Modelo Ausente",
        discrepancy.provider,
        discrepancy.model,
        "-",
        "-",
        "-",
        location,
        action
      ];
      sheet.appendRow(row);
    } else if (discrepancy.type === "status") {
      const location = `${COMPARE_CONFIG.SOURCE_SHEET_NAME} (${_columnToLetter(discrepancy.columnIndex)}${discrepancy.sourceRowIndex}) vs ${COMPARE_CONFIG.TARGET_SHEET_NAME} (${_columnToLetter(discrepancy.columnIndex)}${discrepancy.targetRowIndex})`;
      
      const action = `Alinhar o status de ${discrepancy.capability} para o modelo ${discrepancy.model}`;
      
      row = [
        "Status Divergente",
        discrepancy.provider,
        discrepancy.model,
        discrepancy.capability,
        discrepancy.sourceStatus,
        discrepancy.targetStatus,
        location,
        action
      ];
      sheet.appendRow(row);
      
      // Colorir as células de status de acordo com o valor (Enable/Disable)
      const currentRow = sheet.getLastRow();
      
      // Colorir a célula do status na planilha fonte
      const sourceStatusCell = sheet.getRange(currentRow, 5);
      if (discrepancy.sourceStatus === COMPARE_CONFIG.STATUS.ENABLE) {
        sourceStatusCell.setBackground(COMPARE_CONFIG.COLORS.ENABLE_BG);
      } else if (discrepancy.sourceStatus === COMPARE_CONFIG.STATUS.DISABLE) {
        sourceStatusCell.setBackground(COMPARE_CONFIG.COLORS.DISABLE_BG);
      }
      
      // Colorir a célula do status na planilha alvo
      const targetStatusCell = sheet.getRange(currentRow, 6);
      if (discrepancy.targetStatus === COMPARE_CONFIG.STATUS.ENABLE) {
        targetStatusCell.setBackground(COMPARE_CONFIG.COLORS.ENABLE_BG);
      } else if (discrepancy.targetStatus === COMPARE_CONFIG.STATUS.DISABLE) {
        targetStatusCell.setBackground(COMPARE_CONFIG.COLORS.DISABLE_BG);
      }
    }
    
    rowIndex++;
  });
}

/**
 * Formats the report for better readability
 * @param {Object} sheet - Report sheet object
 * @private
 */
function _formatReport(sheet) {
  const lastRow = sheet.getLastRow();
  const lastColumn = 8; // Number of columns in report
  
  // Set column widths
  sheet.setColumnWidth(1, 150); // Type
  sheet.setColumnWidth(2, 120); // Provider
  sheet.setColumnWidth(3, 200); // Model
  sheet.setColumnWidth(4, 150); // Capability
  sheet.setColumnWidth(5, 150); // Source Status
  sheet.setColumnWidth(6, 150); // Target Status
  sheet.setColumnWidth(7, 250); // Location
  sheet.setColumnWidth(8, 250); // Recommended Action
  
  // Apply borders and background color
  const dataRange = sheet.getRange(4, 1, lastRow - 3, lastColumn);
  dataRange.setBorder(true, true, true, true, true, true);
  
  // Set light background color for data rows (except status cells that are already colored)
  const lightErrorColor = "#FFE6E6"; // Lighter red
  
  // Apply to all rows first
  sheet.getRange(5, 1, lastRow - 4, lastColumn).setBackground(lightErrorColor);
  
  // Center align all cells
  sheet.getRange(1, 1, lastRow, lastColumn).setHorizontalAlignment("center");
  sheet.getRange(1, 1, lastRow, lastColumn).setVerticalAlignment("middle");
  
  // Left align text in the action column
  sheet.getRange(5, 8, lastRow - 4, 1).setHorizontalAlignment("left");
  
  // Enable text wrapping
  sheet.getRange(4, 1, lastRow - 3, lastColumn).setWrap(true);
  
  // Add alternating row colors for better readability
  for (let i = 5; i <= lastRow; i += 2) {
    if (i <= lastRow) {
      // Skip coloring the status cells (columns 5 and 6)
      sheet.getRange(i, 1, 1, 4).setBackground("#F8F8F8");
      sheet.getRange(i, 7, 1, 2).setBackground("#F8F8F8");
    }
  }
}

/**
 * Converts column index to letter (e.g., 1 -> A, 2 -> B)
 * @param {number} column - Column index
 * @return {string} Column letter
 * @private
 */
function _columnToLetter(column) {
  let temp, letter = '';
  while (column > 0) {
    temp = (column - 1) % 26;
    letter = String.fromCharCode(temp + 65) + letter;
    column = (column - temp - 1) / 26;
  }
  return letter;
}

/**
 * Checks if two arrays are equal
 * @param {Array} arr1 - First array
 * @param {Array} arr2 - Second array
 * @return {boolean} True if arrays are equal
 * @private
 */
function _arraysEqual(arr1, arr2) {
  if (arr1.length !== arr2.length) return false;
  
  for (let i = 0; i < arr1.length; i++) {
    if (arr1[i] !== arr2[i]) return false;
  }
  
  return true;
}